#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# Stages — release secrets for Whamp/pi-extensions
#
# Creates the two tokens the release train needs, writes them as GitHub
# Actions repo secrets, stores them in Agent Vault, and attaches the vault
# services that make them usable through the proxy.
#
# Re-run any time to rotate either token: every write is an upsert.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# gh resolves the target repository without leaving this checkout.
export GH_REPO="Whamp/pi-extensions"
REPO="$GH_REPO"

VAULT_WRITTEN=()
VAULT_SKIPPED=()

# npm_auth_check TOKEN — succeed when the token authenticates as whamp.
npm_auth_check() {
  local tmpdir rc
  tmpdir="$(mktemp -d)"
  printf '//registry.npmjs.org/:_authToken=%s\n' "$1" > "$tmpdir/.npmrc"
  chmod 600 "$tmpdir/.npmrc"
  rc=0
  (cd "$tmpdir" && npm whoami 2>/dev/null) | grep -qx 'whamp' || rc=1
  rm -rf "$tmpdir"
  return "$rc"
}

# github_auth_check TOKEN — succeed when the token is Whamp's with push access.
github_auth_check() {
  local login push
  login="$(GH_TOKEN="$1" gh api user --jq .login 2>/dev/null || true)"
  [[ "$login" == "Whamp" ]] || return 1
  push="$(GH_TOKEN="$1" gh api "repos/$REPO" --jq '.permissions.push' 2>/dev/null || true)"
  [[ "$push" == "true" ]]
}

# Agent Vault connection details come from the shared agent-vault-secret config.
VAULT_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/agent-vault-secret/config"
vault_cfg() {
  [[ -f "$VAULT_CONFIG" ]] || return 0
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$VAULT_CONFIG" | tail -n1
}
VAULT_HOST="${AGENT_VAULT_SECRET_HOST:-$(vault_cfg host)}"
VAULT_USER="${AGENT_VAULT_SECRET_SSH_USER:-$(vault_cfg ssh_user)}"
VAULT_CONTAINER="${AGENT_VAULT_SECRET_CONTAINER:-$(vault_cfg container)}"
VAULT_NAME="${AGENT_VAULT_SECRET_VAULT:-$(vault_cfg vault)}"

vault_ready() {
  [[ -n "$VAULT_HOST" && -n "$VAULT_USER" && -n "$VAULT_CONTAINER" && -n "$VAULT_NAME" ]]
}

# vault_remote COMMAND — run an agent-vault subcommand inside the container.
vault_remote() {
  # shellcheck disable=SC2029 # the subcommand is built on this host on purpose
  ssh -o BatchMode=yes -o IdentitiesOnly=yes -o ConnectTimeout=25 \
    "$VAULT_USER@$VAULT_HOST" \
    "docker exec $VAULT_CONTAINER agent-vault $1"
}

# vault_set KEY VALUE — upsert a credential; the value travels on stdin.
vault_set() {
  # shellcheck disable=SC2029 # the credential name is a validated identifier
  if printf '%s\n' "$2" | ssh -o BatchMode=yes -o IdentitiesOnly=yes -o ConnectTimeout=25 \
      "$VAULT_USER@$VAULT_HOST" \
      "read -r __v && docker exec $VAULT_CONTAINER agent-vault vault credential set --vault $VAULT_NAME \"$1=\$__v\"" >/dev/null 2>&1; then
    printf '  %s✓ stored%s %s in vault %s\n' "$GREEN" "$RESET" "$1" "$VAULT_NAME"
    VAULT_WRITTEN+=("$1")
  else
    warn "could not store $1 in Agent Vault"
    VAULT_SKIPPED+=("$1")
  fi
}

# vault_service NAME HOST TOKEN_KEY — attach a credential to a host, idempotently.
vault_service() {
  if vault_remote "vault service list" 2>/dev/null | grep -q "name: $1\$"; then
    printf '  %s✓ service%s %s already present\n' "$GREEN" "$RESET" "$1"
    return 0
  fi
  if vault_remote "vault service add --name $1 --host '$2' --auth-type bearer --token-key $3" >/dev/null 2>&1; then
    printf '  %s✓ service%s %s → %s\n' "$GREEN" "$RESET" "$1" "$2"
  else
    warn "could not add service $1 — see the agent-vault-secret skill"
    VAULT_SKIPPED+=("service $1")
  fi
}

banner "Release secrets — Whamp/pi-extensions"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "npm — create the publish token"
say "CI publishes @whamp/* packages with this token. npm shows the value once."
open_url "https://www.npmjs.com/settings/whamp/tokens"
step "Sign in as whamp if prompted, then click 'Generate New Token' → 'Granular Access Token'."
step "Name it 'pi-extensions-ci' and set an expiration date — 365 days keeps rotation annual."
step "Under 'Packages and scopes', set Permissions to 'Read and write'."
step "Choose 'Only select packages and scopes' and add the '@whamp' scope."
step "Leave Organizations at 'No access'."
step "Turn ON 'Bypass 2FA' — npm requires it for token publishes and CI cannot answer a prompt."
step "Click 'Generate token', then copy the value."
ask_secret NPM_TOKEN "Paste the npm token:"
if [[ -z "$NPM_TOKEN" ]]; then warn "nothing pasted — re-run when ready"; exit 1; fi
note "Checking the token against the registry (safe to skip if this host is offline)…"
if npm_auth_check "$NPM_TOKEN"; then
  printf '  %s✓ token authenticates as whamp%s\n' "$GREEN" "$RESET"
else
  warn "the registry did not accept the token as user whamp"
  confirm "Continue anyway and store it?" || { warn "stopped before writing anything"; exit 1; }
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "GitHub — create the release token"
say "This PAT lets Actions open the Version packages PR and push the tags that trigger publish."
open_url "https://github.com/settings/personal-access-tokens/new?name=pi-extensions-release&description=Open+release+PRs+and+push+package+tags+for+Whamp%2Fpi-extensions&expires_in=365&contents=write&pull_requests=write&workflows=write"
step "Confirm the prefilled name, description, and 365-day expiration."
step "Repository access: choose 'Only select repositories' and pick 'Whamp/pi-extensions' (not prefilled)."
step "Check Repository permissions: Contents Read and write, Pull requests Read and write, Workflows Read and write, Metadata Read."
step "Click 'Generate token', then copy the value."
ask_secret RELEASE_TOKEN "Paste the GitHub token:"
if [[ -z "$RELEASE_TOKEN" ]]; then warn "nothing pasted — re-run when ready"; exit 1; fi
note "Checking the token against the GitHub API…"
if github_auth_check "$RELEASE_TOKEN"; then
  printf '  %s✓ token is Whamp and can push to %s%s\n' "$GREEN" "$REPO" "$RESET"
else
  warn "GitHub did not confirm Whamp plus push access for this token"
  confirm "Continue anyway and store it?" || { warn "stopped before writing anything"; exit 1; }
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "GitHub — write the repo secrets"
say "Both values go to Actions secrets on $REPO; they are piped to gh, never echoed."
set_secret NPM_TOKEN "$NPM_TOKEN"
set_secret RELEASE_TOKEN "$RELEASE_TOKEN"
note "Secrets on $REPO now:"
gh secret list --repo "$REPO" 2>/dev/null | sed 's/^/    /' || warn "could not list secrets"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Agent Vault — store the credentials"
if ! vault_ready; then
  warn "Agent Vault is not configured on this host — see the agent-vault-secret skill"
  VAULT_SKIPPED+=("vault credentials")
else
  say "Upserting both tokens in vault '$VAULT_NAME' on $VAULT_HOST; values travel on stdin."
  vault_set NPM_TOKEN "$NPM_TOKEN"
  vault_set RELEASE_TOKEN "$RELEASE_TOKEN"
fi

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Agent Vault — attach the services"
if ! vault_ready; then
  warn "Agent Vault is not configured; nothing to attach"
else
  say "A credential stays inert until a service binds it to a host."
  vault_service npm-registry "registry.npmjs.org/*" NPM_TOKEN
  vault_service github-api "api.github.com/*" RELEASE_TOKEN
  note "Vault services:"
  vault_remote "vault service list" 2>/dev/null | sed 's/^/    /' || true
fi

finish

if (( ${#VAULT_WRITTEN[@]} )); then
  note "vault credentials written: ${VAULT_WRITTEN[*]}"
fi
if (( ${#VAULT_SKIPPED[@]} )); then
  warn "vault work still to do: ${VAULT_SKIPPED[*]}"
fi
